#!/usr/bin/env bash
# take domain & subdomain as input and
# prints out thier info

subdomains=("www" "lb-01" "web-01" "web-02")

output () {
    domain="$1"
    sub="$2"
    dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | sed -r "s/$sub./$sub/g" |  awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to "$5 }'
}

# loop through the subdomains array
for sub in "${subdomains[@]}"
do
    output "$1" "$sub"
done
