#!/usr/bin/env bash
# take domain & subdomain as input and
# prints out thier info

subdomains=("www" "lb-01" "web-01" "web-02")
domain="$1"
sub="$2"

domain_info () {
    sub="$2"
    INFO="$(dig "$sub.$domain" | grep -A 1 'ANSWER SECTION:' | awk 'NR == 2')"
    IP="$(echo "$INFO" | awk '{print $5}')"
    RECO="$(echo "$INFO" | awk '{print $4}')"

    echo "The subdomain $sub is a $RECO record and points to $IP"
}

if [ $# -eq 1 ]; then
    for sub in "${subdomains[@]}"; do
        domain_info "$sub" "$sub"
    done
elif [ $# -eq 2 ]; then
    domain_info "$sub" "$domain"
fi