#!/usr/bin/env bash
# script to copy a file from a client to a server using scp

# file path and server connection details
FILE_PATH="$1"
IP="$2"
USERNAME="$3"
KEY_PATH="$4"

# check if all required parameters are provided
if [ "$#" -eq 4 ]; then
    # use scp to transfer the file to the server with strict host key checking disabled
    scp -i "$KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME"@"$IP":~/
else
    # display usage instructions when incorrect parameters are given
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
