#!/bin/bash

if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# transfer the fil using scp with strict key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/ || {
  echo "Error: File transfer failed."
  exit 1
}

echo "File $file_path transferred successfully to $username@$server_ip:~/"
