#!/usr/bin/env bash
YELLOW='\e[33m'
GREEN='\e[32m'
NC='\e[0m'


echo -e "${YELLOW}[!] updating your system and installing the nginx${NC}"
sudo apt-get update -y
sudo apt-get install nginx -y
echo -e "${GREEN}[+] nginx installed${NC}"


echo -e "$YELLOW [!] starting the nigx"
sudo service nginx start

echo -e "$YELLOW [!] allowing the nigx on the firewall $NC"
sudo ufw allow 'Nginx HTTP'
echo -e "$YELLOW [!] done allowing the nigx on the firewall${NC}"

echo -e "$YELLOW [!] write hello world"
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx reload
echo -e "$YELLOW [!] done${NC}"