#!/bin/bash

if ! [ -x "$(command -v nginx)" ]; then
    apt-get update
    apt-get install -y nginx

    service nginx start
fi

cat > /etc/nginx/sites-available/redirect_me <<EOL
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        return 404;
    }
}
EOL

ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

nginx -t

nginx -s reload
