#!/usr/bin/env bash
# Install Nginx on the web server

# Updating and installing Nginx
echo "[!] Updating your system and installing Nginx"
sudo apt-get update -y
sudo apt-get install nginx -y
echo "[+] Nginx installed"

# Starting Nginx
echo "[!] Starting Nginx"
sudo service nginx start

# Allowing Nginx through the firewall
echo "[!] Allowing Nginx on the firewall"
sudo ufw allow 'Nginx HTTP'
echo "[!] Done allowing Nginx on the firewall"

# Creating a Hello World page
echo "[!] Creating a Hello World page"
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx reload
echo "[!] Done"
