#!/usr/bin/env bash
# Install Nginx on the web server and configure redirection

# Update and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Start Nginx
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a Hello World page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure redirection to YouTube
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Reload Nginx to apply changes
sudo service nginx reload

# Display completion message
echo "Nginx installation and configuration completed."
