#!/usr/bin/env bash
# install Nginx on the web server and configure redirection and 404 page

# update and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# start Nginx
sudo service nginx start

# allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# create a Hello World page
echo "Hello World!" | sudo tee /var/www/html/index.html

# configure redirection to YouTube
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# set up a custom 404 page
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' /etc/nginx/sites-available/default
sudo sed -i 's/=404/@404/g' /etc/nginx/sites-available/default

# reload Nginx to apply changes
sudo service nginx reload
