#!/usr/bin/env bash
# Define color variables for formatting output
green='\033[0;34m'
red='\033[0;31m'
yellow='\033[1;33m'

# Function to print colored text
cprint() {
  local color=$1
  local text=$2
  local NC='\033[0m'
  echo -e "${color}${text}${NC}"
}

# Start of system update and haproxy installation process

cprint "$green" "[+] Initiating system update and haproxy installation..."

# Function to check if a command is installed
checker() {
  if command -v "$1" >/dev/null 2>&1 ; then
    cprint "$green" "[+] $1 is already installed"
    cprint "$yellow" "[!] Updating installed packages"
    sudo apt-get update -y && \
      sudo apt-get upgrade -y
    sudo apt-get update -y && \
      sudo apt-get upgrade -y
  else
    cprint "$red" "[+] $1 is not installed"
    cprint "$yellow" "[!] Installing $1"
    sudo apt-get update -y && \
      sudo apt-get install "$1" -y
    sudo apt-get update -y && \
      sudo apt-get upgrade -y && \
      sudo apt-get install "$1" -y
    echo -e "\n"
    cprint "$green" "[+] $1 is now installed"
  fi
}

# Check if haproxy is installed
checker haproxy

# Setting up additional configurations

cprint "$yellow" "[!] Configuring some minor settings"

# Backing up the default haproxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Setting new configuration for haproxy
server_config=\
"
defaults
    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s

frontend th3gr00t-tech-frontend
    bind *:80
    default_backend th3gr00t-tech-backend

backend th3gr00t-tech-backend
    balance roundrobin
    server 369995-web-01 54.90.63.243:80 check
    server 369995-web-54.90.4.180:80 check
"
# Use 'dd' to write the new configuration to haproxy.cfg
# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable haproxy
echo "ENABLED=1" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Check if haproxy is running and restart if necessary
if [ "$(pgrep haproxy)" ]; then
  cprint "$green" "[+] haproxy is running"
  sudo service haproxy start
else
  cprint "$red" "[+] Restarting haproxy"
  sudo service haproxy restart
fi
