#!/bin/bash
# bad luck for every country

h=0
m=1

while((i <= 12 ))
do
    echo "Hour: $i"

        while(( m <= 59 ))
        do
            echo $m
            ((m++))
        done
        m=1

    ((i++))

done



