#!/usr/bin/bash
# install the ufw firewall and setting up ufw for web-01
sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable -y
sudo ufw status
